/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PhotonMagic {
        "alterChannel": (channel_index: number) => Promise<void>;
        "loadFile": (file: File) => Promise<void>;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPhotonMagicElement extends Components.PhotonMagic, HTMLStencilElement {
    }
    var HTMLPhotonMagicElement: {
        prototype: HTMLPhotonMagicElement;
        new (): HTMLPhotonMagicElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "photon-magic": HTMLPhotonMagicElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PhotonMagic {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "photon-magic": PhotonMagic;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "photon-magic": LocalJSX.PhotonMagic & JSXBase.HTMLAttributes<HTMLPhotonMagicElement>;
        }
    }
}
